apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.eip.work/layer: web
    k8s.eip.work/name: cetus-customer-prod
  name: cetus-customer-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.eip.work/layer: web
      k8s.eip.work/name: cetus-customer-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
    spec:
      containers:
        - env:
            - name: WHEELJACK_REGISTRY_HOST
              value: orion-metadata-eureka1
            - name: WHEELJACK_REGISTRY_PORT
              value: '8191'
            - name: PROFILE
              value: mysqlstg
            - name: SERVICE_NAME
              value: cetus-customer-service
          image: '10.0.11.210/cetus-mysqldev/cetus-customer-dev:13'
          imagePullPolicy: Always
          name: cetus-customer-prod
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: 210registry
      restartPolicy: Always
      terminationGracePeriodSeconds: 30


---

apiVersion: v1
kind: Service
metadata:
  name: cetus-customer-prod
spec:
  ports:
    - port: 8193
      protocol: TCP
      targetPort: 8193
  selector:
    k8s.eip.work/layer: web
    k8s.eip.work/name: cetus-customer-prod
