apiVersion: apps/v1
kind: Deployment
metadata:
  name: cetus-customer-prod
  labels:
    app: cetus-customer-prod
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: cetus-customer-prod
  template:
    metadata:
      labels:
        app: cetus-customer-prod
    spec:
      containers:
        - env:
            - name: WHEELJACK_REGISTRY_HOST
              value: orion-metadata-eureka1
            - name: WHEELJACK_REGISTRY_PORT
              value: '8191'
            - name: PROFILE
              value: mysqlstg
            - name: SERVICE_NAME
              value: cetus-customer-service
        - name: cetus-customer-prod
          image: 10.0.11.210/cetus-mysqldev/cetus-customer-dev:13
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: cetus-customer-prod
spec:
  selector:
    app: cetus-customer-prod
  ports:
    - protocol: TCP
      port: 8193
      targetPort: 8193
