apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '22'
  creationTimestamp: '2020-10-09T06:03:39Z'
  generation: 46
  labels:
    k8s.eip.work/layer: web
    k8s.eip.work/name: cetus-customer-batch
  name: cetus-customer-batch
  namespace: xinyidai-stg
  resourceVersion: '187376553'
  selfLink: /apis/apps/v1/namespaces/xinyidai-stg/deployments/cetus-customer-batch
  uid: 292463a1-1ddf-447a-bd2c-b177b9808c84
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.eip.work/layer: web
      k8s.eip.work/name: cetus-customer-batch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.eip.work/layer: web
        k8s.eip.work/name: cetus-customer-batch
    spec:
      containers:
        - env:
            - name: WHEELJACK_REGISTRY_HOST
              value: orion-metadata-eureka1
            - name: WHEELJACK_REGISTRY_PORT
              value: '8191'
            - name: PROFILE
              value: mysqlstg
            - name: SERVICE_NAME
              value: cetus-customer-batch
            - name: CUSTOMER_CONTROL_CENTER
              value: 'http://job-admin-svc:8887/orion-job-admin'
            - name: aliyun_logs_cetus-batch
              value: stdout
          image: '10.0.11.210/cetus-mysqldev/cetus-batch-dev:7'
          imagePullPolicy: Always
          name: cetus-customer-batch
          ports:
            - containerPort: 8080
              name: test
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: 210registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-10-10T02:01:03Z'
      lastUpdateTime: '2020-10-12T03:00:11Z'
      message: >-
        ReplicaSet "cetus-customer-batch-5df968dc48" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2020-10-12T06:49:00Z'
      lastUpdateTime: '2020-10-12T06:49:00Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 46
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
